### ISSUE TITLE
这是什么原因呢

### ISSUE THREAD

**Issue by CraneSleep** [wxy1343/ManifestAutoUpdate#13]
![image](https://user-images.githubusercontent.com/83820216/215794978-14eedb04-739e-46a6-aee2-10fb2521101d.png)
报错
appid: 1817070
Traceback (most recent call last):
  File "storage.py", line 130, in <module>
  File "storage.py", line 103, in main
  File "storage.py", line 81, in stool_add
sqlite3.OperationalError: unable to open database file
请按任意键继续. . .

**Comment by wxy1343** [comment]
没装steamtools

**Comment by huayundu** [comment]
> 

steamtools现在用不了了怎么办
