### ISSUE TITLE
无法入库

### ISSUE THREAD

**Issue by hll20090609** [wxy1343/ManifestAutoUpdate#6]
一入库就报这个
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 386, in _make_request
  File "urllib3\connectionpool.py", line 1042, in _validate_conn
  File "urllib3\connection.py", line 414, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 513, in wrap_socket
  File "ssl.py", line 1071, in _create
  File "ssl.py", line 1342, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 489, in send
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/wxy1343/ManifestAutoUpdate/branches/636480 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "storage.py", line 130, in <module>
  File "storage.py", line 97, in main
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 587, in request
  File "requests\sessions.py", line 701, in send
  File "requests\adapters.py", line 563, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/wxy1343/ManifestAutoUpdate/branches/636480 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

**Comment by wxy1343** [comment]
加速github

**Comment by pjy612** [comment]
> 加速github

大佬真辛苦...

**Comment by hll20090609** [comment]
大佬还是要再问一句，成功入库之后再启动steam库当中并没有相应的游戏，steamtools我也开了解锁模式

**Comment by wxy1343** [comment]
> 大佬还是要再问一句，成功入库之后再启动steam库当中并没有相应的游戏，steamtools我也开了解锁模式

steamtools没导入成功，你自己拖一下

**Comment by hll20090609** [comment]
大佬怎么拖啊..........

**Comment by wxy1343** [comment]
> 大佬怎么拖啊..........

https://bbs.steamtools.net/forum.php?mod=viewthread&tid=7797

**Comment by hll20090609** [comment]
大佬问题在于说我库里压根就没有想入库的游戏，拖都没法弄

**Comment by Ahusm** [comment]
请问你解决了吗？我跟你一样的报错信息，今天创的小号，下载过一个游戏（eraser），不知道怎么办
