### ISSUE TITLE
入库失败，请问该怎么解决

### ISSUE THREAD

**Issue by kadidala** [wxy1343/ManifestAutoUpdate#696]
appid: 2066020
Traceback (most recent call last):
  File "storage.py", line 130, in <module>
  File "storage.py", line 103, in main
  File "storage.py", line 81, in stool_add
sqlite3.OperationalError: unable to open database file
请按任意键继续. . .

**Comment by kadidala** [comment]
appid: 2066020
密钥下载成功: config.vdf
Traceback (most recent call last):
  File "storage.py", line 51, in get_manifest
  File "storage.py", line 73, in depotkey_merge
KeyError: 'depots'
清单下载成功: 2066022_6995591316754638194.manifest
清单下载成功: 2066023_5974942034438983303.manifest
清单下载成功: 2066021_8614332541534895293.manifest
入库失败: 2066020
请按任意键继续. . .

**Comment by wxy1343** [comment]
> appid: 2066020 Traceback (most recent call last): File "storage.py", line 130, in File "storage.py", line 103, in main File "storage.py", line 81, in stool_add sqlite3.OperationalError: unable to open database file 请按任意键继续. . .

#13

**Comment by wxy1343** [comment]
> appid: 2066020 密钥下载成功: config.vdf Traceback (most recent call last): File "storage.py", line 51, in get_manifest File "storage.py", line 73, in depotkey_merge KeyError: 'depots' 清单下载成功: 2066022_6995591316754638194.manifest 清单下载成功: 2066023_5974942034438983303.manifest 清单下载成功: 2066021_8614332541534895293.manifest 入库失败: 2066020 请按任意键继续. . .

steam没下载过游戏

**Comment by kadidala** [comment]
> > appid: 2066020 密钥下载成功: config.vdf Traceback (most recent call last): File "storage.py", line 51, in get_manifest File "storage.py", line 73, in depotkey_merge KeyError: 'depots' 清单下载成功: 2066022_6995591316754638194.manifest 清单下载成功: 2066023_5974942034438983303.manifest 清单下载成功: 2066021_8614332541534895293.manifest 入库失败: 2066020 请按任意键继续. . .
> 
> steam没下载过游戏

谢谢解答！新版Steam下载一个游戏后入库正常了，但是我用旧版Steam还是不行，入库正常但是不显示库存，下载几个游戏后也是不显示入库的游戏，请问该如何解决？

**Comment by wxy1343** [comment]
steamtools问题
