### ISSUE TITLE
您好 我入库的时候出现了一个问题显示为KeyError: 'depots'

### ISSUE THREAD

**Issue by GuardMorning** [wxy1343/ManifestAutoUpdate#712]
清单下载成功: 220211_3901531883767526193.manifest
密钥下载成功: config.vdf
Traceback (most recent call last):
  File "storage.py", line 51, in get_manifest
  File "storage.py", line 73, in depotkey_merge
KeyError: 'depots'
清单下载成功: 220212_78739687081486078.manifest
清单下载成功: 220213_1660641291841592914.manifest
清单下载成功: 1998022_9108999533983205102.manifest
清单下载成功: 220217_1542059352249819159.manifest
清单下载成功: 220201_6331816835925954858.manifest
清单下载成功: 220210_5206490517007059532.manifest
清单下载成功: 220209_2010052161041755576.manifest
清单下载成功: 220207_8266439066111296104.manifest
清单下载成功: 220205_8073598277300090923.manifest
清单下载成功: 220208_6506278945653714142.manifest
清单下载成功: 220202_6145727205642015120.manifest
清单下载成功: 220204_895421221909357680.manifest
清单下载成功: 220214_8229629602796981387.manifest
清单下载成功: 220206_939141202072334643.manifest
清单下载成功: 220215_4776840543670162301.manifest
清单下载成功: 220203_5744742415595933520.manifest
入库失败: 220200
请按任意键继续. . .

请问下这该怎么处理

**Comment by wxy1343** [comment]
#13

**Comment by wxy1343** [comment]
#696
