### ISSUE TITLE
怎么办？

### ISSUE THREAD

**Issue by luckyEason** [wxy1343/ManifestAutoUpdate#753]
appid: 431960
Traceback (most recent call last):
  File "D:\ManifestAutoUpdate-main\storage.py", line 179, in <module>
    main(args.app_id or input('appid: '))
  File "D:\ManifestAutoUpdate-main\storage.py", line 117, in main
    stool_add([(app_id, '1', None)])
  File "D:\ManifestAutoUpdate-main\storage.py", line 91, in stool_add
    conn = sqlite3.connect(info_path)
sqlite3.OperationalError: unable to open database file
请按任意键继续. . .
![屏幕截图 2023-04-05 121709](https://user-images.githubusercontent.com/109937362/229979760-4045cdb5-69d4-4bfc-bd59-51dc7f976ea6.png)

**Comment by wxy1343** [comment]
#696

**Comment by luckyEason** [comment]
遇到了新的问题
appid: 431960
已存在清单: 431961_1331544969901301958.manifest
已存在清单: 431966_847479879245171687.manifest
密钥下载成功: config.vdf
Traceback (most recent call last):
  File "D:\ManifestAutoUpdate-main\storage.py", line 57, in get_manifest
    if depotkey_merge(steam_path / 'config' / path, depots_config):
  File "D:\ManifestAutoUpdate-main\storage.py", line 78, in depotkey_merge
    software = config['InstallConfigStore']['Software']
KeyError: 'InstallConfigStore'
入库失败: 431960
![屏幕截图 2023-04-09 125206](https://user-images.githubusercontent.com/109937362/230755017-b4ef074b-c47d-42ff-89c0-a955caf0e0c4.png)

**Comment by wxy1343** [comment]
config.vdf有问题

**Comment by luckyEason** [comment]
> config.vdf有问题

我应该怎么办

**Comment by wxy1343** [comment]
运行一次steam
